input: joystick/xpad: Fix compilation errors
(Temp fix) REVERT UPSTREAM CHANGES FROM: v.103 + v.107

/home/pacmm79/ANDROID/gohan/kernel/drivers/input/joystick/xpad.c: In function 'xpad_init_input':
/home/pacmm79/ANDROID/gohan/kernel/drivers/input/joystick/xpad.c:1110:6: error: 'intf' undeclared (first use in this function)
  if (intf->cur_altsetting->desc.bNumEndpoints != 2)

/home/pacmm79/ANDROID/gohan/kernel/drivers/input/joystick/xpad.c: In function 'xpad_init_input':
/home/pacmm79/ANDROID/gohan/kernel/drivers/input/joystick/xpad.c:1117:18: error: 'udev' undeclared (first use in this function)
  usb_to_input_id(udev, &input_dev->id);
                  ^
/home/pacmm79/ANDROID/gohan/kernel/drivers/input/joystick/xpad.c:1117:18: note: each undeclared identifier is reported only once for each function it appears in
/home/pacmm79/ANDROID/gohan/kernel/drivers/input/joystick/xpad.c:1124:27: error: 'intf' undeclared (first use in this function)
  input_dev->dev.parent = &intf->dev;